"""THE GENERAL BIELLIPTIC TEST, numerically (entry 131; the exact version is compute/qc/bielliptic_test.sage).

A genus-2 curve y^2 = f(x) (deg f = 5 or 6) is bielliptic iff some Moebius involution of P^1 permutes its six branch
points (the roots of f, with infinity when deg f = 5).  A non-hyperelliptic involution of the curve fixes no
Weierstrass point (the stabilizer of a point acts faithfully on the tangent line, so it is cyclic, and it would
contain the Klein group generated by the involution and the hyperelliptic one), so the induced involution of P^1
fixes no branch point: the six points fall into three swapped pairs -- a perfect matching -- and a Moebius map
swapping two given pairs is determined by them (three linear conditions on the four entries) and is an involution.
So: 15 matchings; for each, the map from the first two pairs, tested on the third.  Here the roots are computed to
high precision (mpmath) and a matching passes when the third pair's residual is below a tolerance; a failure of
every matching by a wide margin is a numerical certificate of non-biellipticity (the exact Sage version agrees).

Also: given a rational involution sigma = (ax + b)/(cx - a) with rational fixed points, the substitution sending
them to 0 and infinity gives the even form y^2 = g(x^2) exactly (sympy), the input of the QC pipeline."""
from itertools import combinations
import mpmath as mp
import sympy as sp

mp.mp.dps = 40


def matchings(items):
    if not items:
        yield []
        return
    a = items[0]
    for i in range(1, len(items)):
        rest = items[1:i] + items[i + 1:]
        for m in matchings(rest):
            yield [(a, items[i])] + m


def branch_points(coeffs):
    """Coefficients highest degree first; returns six projective points (X, Z) as mpc pairs."""
    cs = [mp.mpf(c) for c in coeffs]
    while cs and cs[0] == 0:
        cs = cs[1:]
    deg = len(cs) - 1
    assert deg in (5, 6)
    roots = mp.polyroots(cs, maxsteps=200, extraprec=200)
    pts = [(mp.mpc(r), mp.mpc(1)) for r in roots]
    if deg == 5:
        pts.append((mp.mpc(1), mp.mpc(0)))
    return pts


def _cross(v, w):
    return v[0] * w[1] - v[1] * w[0]


def involution_from(P1, Q1, P2, Q2):
    """Least-squares kernel vector of the 3 x 4 system (M P1 ~ Q1, M Q1 ~ P1, M P2 ~ Q2); returns (M, smallest singular value)."""
    rows = []
    for v, w in ((P1, Q1), (Q1, P1), (P2, Q2)):
        rows.append([v[0] * w[1], v[1] * w[1], -v[0] * w[0], -v[1] * w[0]])
    # the kernel of the 3 x 4 system is spanned by the vector of signed 3 x 3 minors (the generalized cross product)
    def det3(m):
        return (m[0][0] * (m[1][1] * m[2][2] - m[1][2] * m[2][1]) - m[0][1] * (m[1][0] * m[2][2] - m[1][2] * m[2][0])
                + m[0][2] * (m[1][0] * m[2][1] - m[1][1] * m[2][0]))
    k = []
    for i in range(4):
        minor = [[r[j] for j in range(4) if j != i] for r in rows]
        k.append((-1) ** i * det3(minor))
    nk = max(abs(v) for v in k)
    if nk == 0:
        return None, None
    M = mp.matrix([[k[0] / nk, k[1] / nk], [k[2] / nk, k[3] / nk]])
    return M, nk


def scan(coeffs, tol=mp.mpf("1e-25")):
    """Returns (n_passing_matchings, min_residual): the residual of a matching is the normalized cross product of
    M * (third pair) against the partner, plus the size of the trace (an involution has trace 0)."""
    pts = branch_points(coeffs)
    scale = max(max(abs(p[0]), abs(p[1])) for p in pts)
    best = None
    n_pass = 0
    for m in matchings(list(range(6))):
        (i1, j1), (i2, j2), (i3, j3) = m
        M, _ = involution_from(pts[i1], pts[j1], pts[i2], pts[j2])
        if M is None:
            continue
        nM = mp.norm(M)
        if nM == 0:
            continue
        res = 0
        for a, b in ((i3, j3), (j3, i3)):
            v = pts[a]
            Mv = (M[0, 0] * v[0] + M[0, 1] * v[1], M[1, 0] * v[0] + M[1, 1] * v[1])
            res = max(res, abs(_cross(Mv, pts[b])) / (nM * max(abs(v[0]), abs(v[1])) * max(abs(pts[b][0]), abs(pts[b][1]))))
        res = max(res, abs(M[0, 0] + M[1, 1]) / nM)
        best = res if best is None else min(best, res)
        if res < tol:
            n_pass += 1
    return n_pass, best


def even_form(coeffs, a, b, c):
    """The rational involution sigma = (a x + b)/(c x - a) (a, b, c rationals with a^2 + bc a rational square) moved
    to x -> -x: returns the even sextic coefficients [g6, g4, g2, g0] of y^2 = g(x'^2) (exact), or None if the
    fixed points are irrational."""
    X, Z = sp.symbols("X Z")
    a, b, c = sp.Rational(a), sp.Rational(b), sp.Rational(c)
    disc = a ** 2 + b * c
    if not sp.sqrt(disc).is_Rational:
        return None
    s = sp.sqrt(disc)
    F = sum(sp.Rational(cf) * X ** k * Z ** (6 - k) for k, cf in enumerate(reversed(list(coeffs))))
    if c != 0:
        p, q = (a + s) / c, (a - s) / c
        G = sp.expand(F.subs({X: q * X - p * Z, Z: X - Z}, simultaneous=True))
    else:
        p = -b / (2 * a)
        G = sp.expand(F.subs({X: X + p * Z}, simultaneous=True))
    P = sp.Poly(G.subs(Z, 1), X)
    cs = [P.coeff_monomial(X ** k) for k in range(7)]
    if any(cs[k] != 0 for k in (1, 3, 5)):
        return None
    return [cs[6], cs[4], cs[2], cs[0]]


if __name__ == "__main__":
    for f in ([25, -36, -18, 44, 1, 0], [25, -4, -18, 12, 1, 0], [1, -4, 6, 12, 1, 0], [1, 0, 11, 0, -5, 0, 1], [1, 0, 0, 0, 1, 0], [1, 0, 0, 1, 0, 0, 8]):
        print(f, scan(f))
    print(even_form([1, 0, 0, 0, 1, 0], 0, 1, 1))
