"""Generate the mod-2^32 magic-square-of-squares witness stored in
verify/targets.py (provenance: this script, deterministic, no randomness).

Theory (docs/foundations/F5-local-solubility.md): any 2-adic unit == 1
(mod 8) is a square in Z_2; entries of L(c,u,v) with c == 1 (mod 8) and
u == v == 0 (mod 8) are all == 1 (mod 8).  This script picks fixed such
(c,u,v), computes an explicit square root of each entry modulo 2^32 by
digit-by-digit lifting, and prints the witness as Python source.

Run:  python3 -m compute.mod2n_lift
"""

N = 32
MOD = 1 << N

# fixed, arbitrary, distinctness-respecting choices (all offsets nonzero,
# pairwise distinct entries mod 2^32):
C = 1 + 8 * 12345
U = 8 * 1729
V = 8 * 9973


def sqrt_mod_2n(a: int, n: int = N) -> int:
    """x with x^2 == a (mod 2^n), for a == 1 (mod 8), by lifting."""
    assert a % 8 == 1
    x = 1
    for k in range(3, n):
        if (x * x - a) % (1 << (k + 1)) != 0:
            x += 1 << (k - 1)
        assert (x * x - a) % (1 << (k + 1)) == 0
    return x % (1 << n)


def entries(c, u, v):
    return [c + u, c - u - v, c + v,
            c - u + v, c, c + u - v,
            c - v, c + u + v, c - u]


def main():
    ents = [e % MOD for e in entries(C, U, V)]
    assert len(set(ents)) == 9, "entries must be distinct mod 2^32"
    roots = [sqrt_mod_2n(e) for e in ents]
    for e, x in zip(ents, roots):
        assert (x * x - e) % MOD == 0
    print(f"# generated by compute/mod2n_lift.py (deterministic)")
    print(f"MOD2N_WITNESS = {{")
    print(f"    'N': {N},")
    print(f"    'c': {C}, 'u': {U}, 'v': {V},")
    print(f"    'entries': {ents},")
    print(f"    'roots': {roots},")
    print(f"}}")


if __name__ == "__main__":
    main()
