"""PARI/GP rank certificates for the transparent primes, and the
general mod-p criterion (entry 79).

THE CRITERION (Rank-r Theorem).  Let p be transparent, E_n: y^2 = x^3
- n^2 x with n = |sqfree(A4)| (isomorphic over Q to y^2 = x^3 - A4^2 x
by x -> x/k^2, y -> y/k^3, k^2 = |A4|/n, p !| k).  Let G_1..G_r be
rational points such that L = <G_1..G_r> + E[2] has ODD index in E(Q)
(2-saturated).  If a solution point P_sol existed, P_sol = P0 + 2Q with
Q in E(Q); reducing mod p (P0 -> T1 = (0,0), P_sol -> O) gives
2 Q~ = T1~.  With d odd and dQ = sum a_i G_i + T:
    T1~ = d T1~ = 2d Q~ = 2 sum a_i G_i~   in   2H,  H = <G_1~..G_r~>.
So   T1~ NOT in 2H   ==>   no solution: the rigidity lemma holds at p.
For r = 1 this is automatic (the Rank-1 Theorem); for r >= 2 it is a
finite computation in E~(F_p) once generators are known.

PARI's ellrank (2-descent + Cassels-Tate) returns [r, R, s, points]
with r <= rank <= R; ellsaturation(E, pts, 2) 2-saturates.  The sweep
output (RES p n r R s [points]) is parsed here and re-verified in
exact arithmetic: points on the curve, descent-image independence,
and the half-test T1~ in 2H by brute-force subgroup closure.
"""
from __future__ import annotations

import json
import re
from fractions import Fraction as Fr

from compute.selmer_descent import descent_image, fp_add

GP = r"C:\Users\Will\pari-2.17.4\gp.exe"


def parse_res_lines(text):
    """RES p n r R s [[x,y],...]  ->  dict p -> record."""
    out = {}
    for line in text.splitlines():
        if not line.startswith("RES "):
            continue
        effort = 0
        if " EFFORT " in line:
            line, _, e = line.rpartition(" EFFORT ")
            effort = int(e)
        head, _, pts = line[4:].partition("[")
        p, n, r, R, s = (int(t) for t in head.split())
        pts = "[" + pts
        points = []
        for m in re.finditer(r"\[\s*([-\d/]+)\s*,\s*([-\d/]+)\s*\]", pts):
            points.append([Fr(m.group(1)), Fr(m.group(2))])
        out[p] = {"n": n, "r": r, "R": R, "s": s, "points": points,
                  "effort": effort}
    return out


def on_curve(P, n):
    x, y = P
    return y * y == x**3 - n * n * x


def reduce_point(P, n, p):
    """Reduction mod p of a rational point of E_n (None = O)."""
    x, y = P
    if x.denominator % p == 0 or y.denominator % p == 0:
        return None
    xm = (x.numerator * pow(x.denominator, -1, p)) % p
    ym = (y.numerator * pow(y.denominator, -1, p)) % p
    assert (ym * ym - (xm**3 - n * n * xm)) % p == 0
    return (xm, ym)


def subgroup_closure(gens, A, p):
    """The subgroup of E~(F_p): y^2 = x^3 + A x generated by gens."""
    H = {None}
    frontier = [None]
    gens = [g for g in gens]
    while frontier:
        nxt = []
        for h in frontier:
            for g in gens:
                s = fp_add(h, g, A, p)
                if s not in H:
                    H.add(s)
                    nxt.append(s)
        frontier = nxt
    return H


def half_test(points, n, p):
    """True iff T1~ = (0,0) is NOT in 2H, H = <reductions of points>:
    the criterion that proves the rigidity lemma at p."""
    A = (-n * n) % p
    gens = [reduce_point(P, n, p) for P in points]
    gens = [g for g in gens if g is not None]
    H = subgroup_closure(gens, A, p)
    doubles = {fp_add(h, h, A, p) for h in H}
    return (0, 0) not in doubles, len(H)


def local_descent_criterion(p, n, S=None):
    """THE DESCENT-LOCAL CRITERION (entry 79) -- needs no generators and
    no rank.  In E~(F_p)/2E~(F_p) = (Z/2)^2 the class of a point not of
    order <= 2 is its descent triple (x, x-n, x+n) read through Legendre
    symbols, and for Q in E(Q) that class equals the localization at p
    of delta(Q) in Sel^2 (the descent diagram commutes with reduction).
    A solution forces Q in E(Q) with 2Q~ = T1~, so Q~ lies in the coset
    Q0~ + E~[2] of a half of T1~; every 2-torsion class is trivial here
    ((n/p) = (2/p) = 1), so [Q~] = [Q0~].  Hence
        [Q0~]  NOT in  lambda_p(Sel^2(E_n))   ==>   no solution.
    Returns (proven, half_class, image) with image = lambda_p(Sel^2)."""
    from compute.selmer_descent import selmer, fp_curve_points, legendre
    A = (-n * n) % p
    assert n % p and legendre(n % p, p) == 1 and legendre(2, p) == 1
    pts = fp_curve_points(n, p)
    T1 = (0, 0)
    halves = [P for P in pts if P is not None and fp_add(P, P, A, p) == T1]
    assert halves, "T1 in 2E~(F_p) fails"

    def cls(P):
        x = P[0]
        return (legendre(x, p), legendre((x - n) % p, p), legendre((x + n) % p, p))

    classes = {cls(P) for P in halves}
    assert len(classes) == 1, classes
    half_class = classes.pop()
    if S is None:
        S = selmer(n)
    image = {(legendre(d1 % p, p), legendre(d2 % p, p), legendre(d3 % p, p))
             for d1, d2, d3 in S}
    return half_class not in image, half_class, image


def independent_mod_torsion(points, n):
    """Descent images of the points span a space of dimension #points
    modulo the torsion images (so the points are independent and
    generate a 2-saturated subgroup together with E[2] iff rank = #points)."""
    tors = {(1, 1, 1)}
    from compute.selmer_descent import sqfree
    vecs = []
    for P in points:
        vecs.append(descent_image(P[0], n))
    # rank of the F2-span of {vecs} modulo the torsion-image subgroup
    nn = n
    tor = [descent_image(Fr(0), nn), descent_image(Fr(nn), nn), descent_image(Fr(-nn), nn)]

    def key(v):
        return tuple(sqfree(t) for t in v)

    # build F2 vector space on the multiplicative group generated by all entries
    primes = set()
    for v in list(vecs) + tor:
        for t in v:
            t = abs(sqfree(t))
            d = 2
            while d * d <= t:
                while t % d == 0:
                    primes.add(d)
                    t //= d
                d += 1
            if t > 1:
                primes.add(t)
    primes = sorted(primes)
    idx = {q: i for i, q in enumerate(primes)}

    def coords(v):
        bits = []
        for t in v:
            t = sqfree(t)
            b = [0] * (len(primes) + 1)
            if t < 0:
                b[-1] = 1
                t = -t
            for q in primes:
                if t % q == 0:
                    b[idx[q]] = 1
            bits.extend(b)
        return bits

    def rank_f2(rows):
        rows = [r[:] for r in rows]
        rk = 0
        ncol = len(rows[0]) if rows else 0
        for c in range(ncol):
            piv = next((i for i in range(rk, len(rows)) if rows[i][c]), None)
            if piv is None:
                continue
            rows[rk], rows[piv] = rows[piv], rows[rk]
            for i in range(len(rows)):
                if i != rk and rows[i][c]:
                    rows[i] = [a ^ b for a, b in zip(rows[i], rows[rk])]
            rk += 1
        return rk

    base = [coords(v) for v in tor]
    r0 = rank_f2(base)
    r1 = rank_f2(base + [coords(v) for v in vecs])
    return r1 - r0 == len(points)


def verify_records(recs, sqfree_of_A4, transparent_A4):
    """Re-verify a parsed sweep in exact arithmetic.  Returns a summary.

    UNCONDITIONAL semantics: PARI's r2 = C - T - s is an unconditional
    upper bound (2-Selmer rank minus torsion minus the Cassels-pairing
    part of Sha[2]); its r1 may use parity.  So the rank is CERTIFIED
    here iff the number of independent points found (independence
    re-verified through descent images) equals r2 -- then rank = r2
    with no conjecture.  Rank 1 certified -> the Rank-1 Theorem proves
    the prime.  Rank >= 2 certified -> the points, 2-saturated by
    ellsaturation, generate an odd-index subgroup and the half-test
    T1~ not in 2H proves the prime (the Rank-r criterion)."""
    out = {}
    for p, rec in recs.items():
        n = rec["n"]
        assert n == sqfree_of_A4[p], (p, n)
        pts = rec["points"]
        for P in pts:
            assert on_curve(P, n), (p, P)
        ok_ind = independent_mod_torsion(pts, n) if pts else True
        assert ok_ind, p
        assert len(pts) <= rec["R"], p
        proven, hsize = (None, None)
        certified = (len(pts) == rec["R"])
        rank = rec["R"] if certified else None
        if certified and rank == 1:
            proven = True          # Rank-1 Theorem
        elif certified and rank >= 2:
            proven, hsize = half_test(pts, n, p)
        out[p] = {"n": n, "r": rec["r"], "R": rec["R"], "s": rec["s"],
                  "npts": len(pts), "independent": ok_ind,
                  "certified": certified, "rank": rank,
                  "proven": proven, "H": hsize, "effort": rec.get("effort", 0)}
    return out


def load_data(path):
    with open(path) as f:
        d = json.load(f)
    for rec in d.values():
        rec["points"] = [[Fr(x), Fr(y)] for x, y in rec["points"]]
    return {int(k): v for k, v in d.items()}


def save_data(path, recs):
    d = {}
    for p, rec in recs.items():
        d[str(p)] = {"n": rec["n"], "r": rec["r"], "R": rec["R"], "s": rec["s"],
                     "effort": rec.get("effort", 0),
                     "points": [[str(x), str(y)] for x, y in rec["points"]]}
    with open(path, "w") as f:
        json.dump(d, f, indent=1)
