"""Rebuild the open research inventory from the authoritative campaign ledgers.

python -m compute.research_inventory             # write deterministic artifacts
python -m compute.research_inventory --check     # detect stale artifacts

This is a projection of current verdicts, not a new arithmetic decision.
The (2,1,1) ledger contains only its 79,368 additional three-frame classes.
"""
import argparse
from collections import Counter
import gzip
import hashlib
import json
from pathlib import Path

from compute.cancellation_patterns import (binomial_constraints, candidate_patterns,
                                            height_direction, square_residue_parameters)
from compute.prime_column import column_certificate

ROOT = Path(__file__).resolve().parents[1]
ARTIFACT = ROOT / "compute/data_research_survivors.json.gz"
REPORT = ROOT / "docs/RESEARCH-INVENTORY.md"
SOURCES = {"111": "compute/data_omega3_box111.json",
           "211": "compute/data_omega3_box211.json.gz"}


def encoded(value):
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode("utf-8")


def digest(value):
    return hashlib.sha256(encoded(value)).hexdigest()


def load_source(path):
    raw = path.read_bytes()
    return json.loads(gzip.decompress(raw) if path.suffix == ".gz" else raw)


def build():
    result = {"schema": 1, "scope": "open finite classes in the two recorded campaigns; not all exponent shapes",
              "meaning_of_finite": "finiteness certificate, not an enumerated rational-point set or an existence claim",
              "sources": {}, "summary": {}, "classes": []}
    for shape, relative in SOURCES.items():
        data = load_source(ROOT / relative)
        result["sources"][shape] = {"path": relative, "semantic_sha256": digest(data),
                                     "scope": "full box" if shape == "111" else "additional three-frame classes only"}
        tally, passed, roles, role_multisets, routes = (Counter() for _ in range(5))
        for index, record in enumerate(data["classes"]):
            verdict = record.get("verdict", record.get("v"))
            tally[verdict] += 1
            certificate = column_certificate(record["cand"][:4])
            if certificate is None:
                passed[verdict] += 1
            if verdict != "finite":
                if verdict != "dead":
                    raise ValueError(f"{shape}:{index}: unhandled verdict {verdict}")
                continue
            if certificate is not None:
                raise ValueError(f"{shape}:{index}: an open class violates A3.PC")
            patterns = candidate_patterns(record["cand"])
            role_word = "".join(p["role"] for p in patterns)
            role_multiset = "".join(sorted(p["role"] for p in patterns))
            roles[role_word] += 1
            role_multisets[role_multiset] += 1
            route = ("compact campaign certificate" if shape == "211" else
                     "hyperelliptic tower" if "towers" in record else "resolved curve and quotients")
            routes[route] += 1
            constraints = binomial_constraints(record["cand"])
            evidence_fields = ("mechanism", "towers", "quotients", "two_step") if shape == "111" else ("c",)
            result["classes"].append({
                "id": f"{shape}:{index}", "shape": shape,
                "source_index": index, "source_record_sha256": digest(record),
                "cand": record["cand"], "verdict": verdict,
                "frame": int(record.get("frame", record.get("f"))),
                "columns": patterns, "role_word": role_word, "role_multiset": role_multiset,
                "full_exponent_every_column": all(p["maximum"] == a for p, a in zip(patterns, map(int, shape))),
                "arithmetic_route": route,
                "binomial_constraints": constraints,
                "binomial_height_recession_direction": height_direction(constraints, len(patterns)),
                "recorded_evidence": {key: record[key] for key in evidence_fields if key in record},
            })
        result["summary"][shape] = {"ledger_classes": sum(tally.values()), "ledger_tally": dict(sorted(tally.items())),
                                     "passes_column_rule": dict(sorted(passed.items())),
                                     "open_role_words": dict(sorted(roles.items())),
                                     "open_role_multisets": dict(sorted(role_multisets.items())),
                                     "open_arithmetic_routes": dict(sorted(routes.items()))}
    return result


def render(data):
    lines = ["# Research inventory after the prime-column lemma", "",
             "Generated by `python -m compute.research_inventory`; verify freshness with `--check`.",
             "The full machine inventory is [data_research_survivors.json.gz](../compute/data_research_survivors.json.gz).",
             "Every open record retains its canonical candidate, source index and hash, signed prime-column patterns, deciding frame, and recorded arithmetic evidence.", "",
             "`finite` means that a finiteness argument is recorded. It does not mean the rational points have been enumerated or that an admissible point exists.", "",
             "| Campaign scope | Ledger classes | Dead | Open finite | Pass A3.PC but already dead |",
             "|---|---:|---:|---:|---:|"]
    for shape, summary in data["summary"].items():
        t = summary["ledger_tally"]
        lines.append(f"| {shape} ({data['sources'][shape]['scope']}) | {summary['ledger_classes']:,} | {t['dead']:,} | {t['finite']:,} | {summary['passes_column_rule'].get('dead', 0):,} |")
    lines += ["", "The second row is an incremental campaign, not the full (2,1,1) box. Counts describe canonical classes, not distinct curves or magic squares.",
              "All sixteen C2 classes closed in entry 118 remain outside this open inventory. Every free-frame class is excluded by A3.PC.", "",
              "## Two complementary ways to read the survivors", "",
              "For cancellation descent, A/B/C/D names the sole label below the column maximum; `*` means four maxima.",
              "A role multiset groups primes by cancellation role only. It does not assert equivalence of the signs, exponent gaps, curves, or rational-point problems. Those distinctions remain in each record.", "",
              "For arithmetic geometry, the evidence retains the existing towers and quotient models. Quotient genus, original-curve genus, and a genus lower bound must remain distinct. In compact (2,1,1) records `bounN` is a lower bound and `resoN` records a resolution result; an untagged `finite` supplies no genus value here.", "",
              "| Campaign | Recorded arithmetic route | Open classes |", "|---|---|---:|"]
    for shape, summary in data["summary"].items():
        for route, count in summary["open_arithmetic_routes"].items():
            lines.append(f"| {shape} | {route} | {count:,} |")
    lines += ["", "## Representatives for independent attacks", "",
              "One representative per role multiset and campaign is listed below. Use all members before claiming a family theorem; this table is a starting set, not a sufficient test suite.", "",
              "| Roles | 111 count / representative | Additional 211 count / representative |", "|---|---|---|"]
    multisets = sorted(set().union(*(s["open_role_multisets"] for s in data["summary"].values())))
    representatives = {}
    for record in data["classes"]:
        representatives.setdefault((record["shape"], record["role_multiset"]), record["id"])
    for roles in multisets:
        cells = []
        for shape in SOURCES:
            count = data["summary"][shape]["open_role_multisets"].get(roles, 0)
            cells.append(f"{count} / `{representatives[shape, roles]}`" if count else "—")
        lines.append(f"| `{roles}` | " + " | ".join(cells) + " |")
    lines += ["", "## Leading-square residue controls", "",
              "These are necessary conditions at a supplied center prime, not exclusions of variable-prime classes. A/B admit a leading-square ray at every split prime. C/D require 2 to be a square, hence p = 1 mod 8. The four-maximum case needs t, 1+t, 1−t all nonzero squares mod p.", "",
              "| Split prime p | A/B possible | C/D possible | Four-maximal parameters t |", "|---:|---|---|---|"]
    for p in (5, 13, 17, 29, 37, 41, 73, 89, 97):
        parameters = square_residue_parameters("*", p)
        lines.append(f"| {p} | yes | {'yes' if square_residue_parameters('C', p) else 'no'} | {', '.join(map(str, parameters)) or 'none'} |")
    directions = Counter(tuple(r["binomial_height_recession_direction"] or []) for r in data["classes"])
    lines += ["", "## First height experiment", "",
              "Each record includes CP.4's explicit unit binomials and necessary norm bounds. An exact positive recession direction means these bounds allow arbitrarily large real log-primes, so they alone cannot give a height cap. It does not construct primes or satisfy the original unit congruences. Four-maximal columns contribute no binomial bounds here; their trinomial equations remain to be used.", "",
              "| Direction for the three log-primes | Open records |", "|---|---:|"]
    for direction, count in sorted(directions.items()):
        lines.append(f"| `{direction}` | {count:,} |" if direction else f"| No witness found in the bounded search | {count:,} |")
    lines += ["", "## Evidence and next questions", "",
              "- [Cancellation descent](attacks/A10-cancellation-descent.md): the valuation support is now classified for the relaxed Laurent system; couple the exact unit congruences across primes.",
              "- Lift-preserving curve descent: the 88 surviving (1,1,1) tower records are the first arithmetic set; inspect their retained square conditions and elliptic ranks before choosing a point algorithm.",
              "- Geometry and global obstructions: use the same candidate IDs to connect quotients, the differential web, and proposed descent invariants. Missing geometry in the compact second campaign is a data gap, not an absence theorem.",
              "- Counterexample tests: include four-maximum and mixed-deficit patterns, the completed C2 family as a retrospective control, and applicable local/near-miss anchors. Record which hypotheses each control satisfies.", "",
              "The [flexible roadmap](ROADMAP.md#r12-current-research-portfolio-2026-09-06) maintains several independent attacks. Inventory size is not the measure of conceptual progress.", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = build()
    raw, report = encoded(data) + b"\n", render(data)
    if args.check:
        if not ARTIFACT.exists() or gzip.decompress(ARTIFACT.read_bytes()) != raw:
            raise SystemExit("stale survivor data: run python -m compute.research_inventory")
        if not REPORT.exists() or REPORT.read_text(encoding="utf-8") != report:
            raise SystemExit("stale research report: run python -m compute.research_inventory")
    else:
        ARTIFACT.write_bytes(gzip.compress(raw, mtime=0))
        REPORT.write_text(report, encoding="utf-8", newline="\n")
    print(f"{'Verified' if args.check else 'Wrote'} {len(data['classes']):,} open records with source hashes and cancellation patterns")


if __name__ == "__main__":
    main()
