"""Complete 2-descent for the congruent-number curve
    E_n : y^2 = x (x - n)(x + n),   n ODD and squarefree,
and the height-argument set-up for the transparent class (entry 76).

Descent map  P = (x, y)  ->  (x, x-n, x+n) in (Q*/Q*^2)^3, with the
2-torsion images (0,0) -> (-1,-n,n), (n,0) -> (n,2,2n),
(-n,0) -> (-n,-2n,2).  The 2-Selmer group is the set of triples
(d1,d2,d3), di in Q(S,2) = <-1, 2, primes of n>, d1 d2 d3 a square,
that are everywhere locally in the image of E(Q_v):
  * odd l | n (additive reduction): the local image is the group of
    order 4 generated by the torsion images, read l-adically;
  * l = 2: the image of order 8, enumerated from 2-adic points
    (including x of negative 2-adic valuation, e.g. x = u/4 with
    u = 1 mod 8 gives the class (1,5,5));
  * infinity: the sign pattern of (x, x-n, x+n) for real x.
rank(E_n) <= dim_2 S - 2.  Controls: n = 1,3,11,19,43 give |S| = 4
(rank 0); n = 5,7,13,15,21,23 give |S| = 8 (rank 1).

THE HEIGHT SET-UP (proven).  A solution of the rigidity endpoint
gives (I, R, X) Pythagorean with R^2 - I^2 = A = p^2 A4, hence the
INTEGRAL point P_sol = (X^2, 2 I R X) on y^2 = x^3 - A^2 x, whose
descent image is (X^2, 2I^2, 2R^2) = (1,2,2).  The frame point
P0 = (p^2, 2 c1 s1 p) has image (p^2, 2 s1^2, 2 c1^2) = (1,2,2) too.
Since ker(delta) = 2E(Q):  P_sol in P0 + 2E(Q).  If rank E = 1, then
P_sol = k G + T0 with k odd, and integrality of odd multiples is the
whole question (an elliptic-divisibility-sequence statement).
"""

from itertools import product
from math import gcd

from compute.quartic_sieve import factor


def sqfree(n):
    s = -1 if n < 0 else 1
    n = abs(n)
    out = s
    for q, e in factor(n)[0].items():
        if e % 2:
            out *= q
    return out


def legendre(a, l):
    a %= l
    if a == 0:
        return 0
    return 1 if pow(a, (l - 1) // 2, l) == 1 else -1


def class_odd(d, l):
    """square class of the integer d in Q_l, l odd: (val mod 2, Legendre of the unit part)"""
    v = 0
    while d % l == 0:
        d //= l
        v += 1
    return (v % 2, legendre(d, l))


def class_2(d):
    """square class of the integer d in Q_2: (val mod 2, unit part mod 8)"""
    v = 0
    while d % 2 == 0:
        d //= 2
        v += 1
    return (v % 2, d % 8)


def two_adic_image(n, prec=10):
    """The image of E_n(Q_2) under (x, x-n, x+n), n odd."""
    assert n % 2 == 1
    M = 2 ** prec
    img = set()
    for v in range(0, 7):
        for u in range(1, M, 2):
            x = (2 ** v) * u
            prod_ = x * (x - n) * (x + n)
            if prod_ == 0:
                continue
            pv, q = 0, prod_
            while q % 2 == 0:
                q //= 2
                pv += 1
            if pv % 2 or q % 8 != 1:
                continue
            triple, ok = [], True
            for z in (x, x - n, x + n):
                zv, zz = 0, z
                while zz % 2 == 0:
                    zz //= 2
                    zv += 1
                    if zv > prec - 4:
                        ok = False
                        break
                if not ok:
                    break
                triple.append((zv % 2, zz % 8))
            if ok:
                img.add(tuple(triple))
    for v in range(2, 9, 2):                # x = u / 2^v, v even
        for u in range(1, 64, 2):
            odd = u * (u * u - (4 ** v) * n * n)
            oo = odd
            while oo % 2 == 0:
                oo //= 2
            if oo % 8 != 1:
                continue
            img.add(tuple((v % 2, (u + s * (2 ** v) * n) % 8)
                          for s in (0, -1, 1)))
    img.add(((0, 1), (0, 1), (0, 1)))
    return img


_REAL_OK = {(True, True, True), (False, False, True),
            (True, False, True), (False, False, False)}


def selmer(n):
    """The 2-Selmer group of E_n (n odd squarefree, taken up to sign)
    as a list of triples (d1, d2, d3)."""
    n = abs(sqfree(n))
    assert n % 2 == 1, "odd n only"
    odd_primes = list(factor(n)[0]) if n > 1 else []
    gens = [-1, 2] + odd_primes
    Q = []
    for mask in product((0, 1), repeat=len(gens)):
        d = 1
        for m, g in zip(mask, gens):
            if m:
                d *= g
        Q.append(d)
    Qset = set(Q)

    def mul(a, b):
        return tuple(((x[0] + y[0]) % 2, x[1] * y[1]) for x, y in zip(a, b))

    loc_odd = {}
    for l in odd_primes:
        T1 = tuple(class_odd(d, l) for d in (n, 2, 2 * n))
        T2 = tuple(class_odd(d, l) for d in (-n, -2 * n, 2))
        one = ((0, 1), (0, 1), (0, 1))
        loc_odd[l] = {one, T1, T2, mul(T1, T2)}
    img2 = two_adic_image(n)
    S = []
    for d1 in Q:
        for d2 in Q:
            d3 = sqfree(d1 * d2)
            if d3 not in Qset:
                continue
            if (d1 > 0, d2 > 0, d3 > 0) not in _REAL_OK:
                continue
            if any(tuple(class_odd(d, l) for d in (d1, d2, d3))
                   not in loc_odd[l] for l in odd_primes):
                continue
            if tuple(class_2(d) for d in (d1, d2, d3)) not in img2:
                continue
            S.append((d1, d2, d3))
    return S


def selmer_rank_bound(n):
    """dim_2 S - 2 >= rank E_n."""
    s = len(selmer(n))
    k = s.bit_length() - 1
    assert 1 << k == s, "Selmer group size not a power of 2?!"
    return k - 2


def descent_image(x, n):
    """(x, x-n, x+n) as squarefree classes, for an integer x."""
    return (sqfree(x), sqfree(x - n), sqfree(x + n))


def frame_point(p, c1, s1):
    """P0 = (p^2, 2 c1 s1 p) on y^2 = x^3 - A4^2 x, A4 = c1^2 - s1^2."""
    return (p * p, 2 * c1 * s1 * p)


def add_points(P, Q, A):
    """Group law on y^2 = x^3 + A x with exact Fractions; None = O."""
    from fractions import Fraction as Fr
    if P is None:
        return Q
    if Q is None:
        return P
    x1, y1 = Fr(P[0]), Fr(P[1])
    x2, y2 = Fr(Q[0]), Fr(Q[1])
    if x1 == x2:
        if y1 == -y2:
            return None
        lam = (3 * x1 * x1 + A) / (2 * y1)
    else:
        lam = (y2 - y1) / (x2 - x1)
    x3 = lam * lam - x1 - x2
    return (x3, lam * (x1 - x3) - y1)
