// Entry 139, follow-up for block J of magma_tower139.m: y^2 = x^5 + 688 x^4 + 3808 x^3 - 10496 x^2 + 6400 x.
// MordellWeilGroupGenus2 returned Z/2 + Z with "group proved: false" and Chabauty returned {(0,0), oo} with index primes {3}:
// the point set is unconditional once the subgroup generated by the found generator (plus torsion) has index prime to 3.
// The torsion is Z/2 (no 3-torsion), so it suffices that neither Q nor Q + T is divisible by 3 in J(Q) (Q the generator,
// T the 2-torsion point): then no rational point R has 3R in <Q> + T with a coefficient prime to 3.
P<x> := PolynomialRing(Rationals());
C := HyperellipticCurve(x^5 + 688*x^4 + 3808*x^3 - 10496*x^2 + 6400*x);
J := Jacobian(C);
G, m, rp, gp := MordellWeilGroupGenus2(J);
print "MW group:", G; print "rank proved:", rp, "group proved:", gp;
free := [G.i : i in [1..Ngens(G)] | Order(G.i) eq 0];
tors := [G.i : i in [1..Ngens(G)] | Order(G.i) ne 0];
Q := m(free[1]);
print "generator Q:", Q;
print "Q divisible by 3?", IsDivisibleBy(Q, 3);
for t in tors do
    T := m(t);
    print "torsion point T:", T;
    print "Q + T divisible by 3?", IsDivisibleBy(Q + T, 3);
end for;
